"""change in service model

Revision ID: 0648306a3ebf
Revises: 459b18665def
Create Date: 2024-11-29 17:10:20.408825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0648306a3ebf'
down_revision = '459b18665def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
