"""change in category model

Revision ID: 06a5c84a6c59
Revises: 7a5d894e5b88
Create Date: 2024-11-09 23:49:51.982629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a5c84a6c59'
down_revision = '7a5d894e5b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('penalty_rate')
        batch_op.drop_column('cancellation_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_rate', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('penalty_rate', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
