"""category model update with new fields

Revision ID: 0816164f8b49
Revises: 5abd03e8656d
Create Date: 2024-10-20 17:39:30.100407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0816164f8b49'
down_revision = '5abd03e8656d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('booking_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penalty_rate', sa.Integer(), nullable=True))
        batch_op.drop_column('commission_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_rate', sa.INTEGER(), nullable=False))
        batch_op.drop_column('penalty_rate')
        batch_op.drop_column('cancellation_rate')
        batch_op.drop_column('transaction_rate')
        batch_op.drop_column('booking_rate')
        batch_op.drop_column('service_rate')

    # ### end Alembic commands ###
