"""avatar remove

Revision ID: 09cf5964f359
Revises: 51b70643c1c3
Create Date: 2024-11-10 15:14:09.740241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cf5964f359'
down_revision = '51b70643c1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
