"""empty message

Revision ID: 20d4efb24150
Revises: 0d8790c52c7a
Create Date: 2024-11-10 18:06:10.497546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d4efb24150'
down_revision = '0d8790c52c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('approved_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
