"""change in booking model

Revision ID: 4290d5685743
Revises: 152532d88099
Create Date: 2024-11-08 17:34:19.424713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4290d5685743'
down_revision = '152532d88099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.String(length=100), nullable=True))
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
