"""few changes in customer's models

Revision ID: 4b7d541ef71d
Revises: c19d2e9d0fc1
Create Date: 2024-10-23 19:33:27.048166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7d541ef71d'
down_revision = 'c19d2e9d0fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('date_scheduled',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('tax',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('tax',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('date_scheduled',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
