"""empty message

Revision ID: 7a5d894e5b88
Revises: 4290d5685743
Create Date: 2024-11-09 18:24:39.945456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5d894e5b88'
down_revision = '4290d5685743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_providers_category_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_providers_category_id', ['category_id'])

    # ### end Alembic commands ###
