"""empty message

Revision ID: b133220cb4f3
Revises: 29049c769d3e
Create Date: 2024-11-05 18:51:23.193851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b133220cb4f3'
down_revision = '29049c769d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_providers_category_id', ['category_id'])
        batch_op.create_unique_constraint('uq_providers_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_providers_user_id', type_='unique')
        batch_op.drop_constraint('uq_providers_category_id', type_='unique')

    # ### end Alembic commands ###
