"""empty message

Revision ID: c19d2e9d0fc1
Revises: ee3aae27bbf7
Create Date: 2024-10-21 18:42:20.114271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19d2e9d0fc1'
down_revision = 'ee3aae27bbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_time_hr', sa.Integer(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_required_hr', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('availability', sa.String(length=50), nullable=True))
        batch_op.drop_column('rate')
        batch_op.drop_column('time_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_required', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('rate', sa.INTEGER(), nullable=False))
        batch_op.drop_column('availability')
        batch_op.drop_column('time_required_hr')
        batch_op.drop_column('price')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('min_time_hr')

    # ### end Alembic commands ###
