"""empty message

Revision ID: d4877d3e9360
Revises: 7e2265a67925
Create Date: 2024-11-21 22:23:44.855033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4877d3e9360'
down_revision = '7e2265a67925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
