"""changes made to booking model and new models introduce

Revision ID: ee3aae27bbf7
Revises: 0816164f8b49
Create Date: 2024-10-21 16:05:48.839683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3aae27bbf7'
down_revision = '0816164f8b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_escrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escrow_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payout_cycle', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cancellation_charge', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_categories')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_scheduled', sa.DateTime(), nullable=False))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('service_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('booking_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('transaction_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cancellation_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('penalty_rate',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=False))
        batch_op.drop_column('commission_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_fee', sa.INTEGER(), nullable=True))
        batch_op.drop_column('tax')
        batch_op.drop_column('transaction_fee')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('penalty_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cancellation_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transaction_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_rate',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('date_scheduled')

    op.create_table('_alembic_tmp_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('commission_rate', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('base_price', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('refunds')
    op.drop_table('provider_payouts')
    op.drop_table('payout_requests')
    op.drop_table('admin_escrows')
    # ### end Alembic commands ###
